// smithy-typescript generated code
export type {
  SustainabilityClient,
  Sustainability,
  GetEstimatedCarbonEmissionsCommand,
  GetEstimatedCarbonEmissionsCommandInput,
  GetEstimatedCarbonEmissionsCommandOutput,
  GetEstimatedCarbonEmissionsDimensionValuesCommand,
  GetEstimatedCarbonEmissionsDimensionValuesCommandInput,
  GetEstimatedCarbonEmissionsDimensionValuesCommandOutput,
  Dimension,
  EmissionsType,
  EmissionsUnit,
  TimeGranularity,
  DimensionEntry,
  Emissions,
  EstimatedCarbonEmissions,
  FilterExpression,
  GetEstimatedCarbonEmissionsDimensionValuesRequest,
  GetEstimatedCarbonEmissionsDimensionValuesResponse,
  GetEstimatedCarbonEmissionsRequest,
  GetEstimatedCarbonEmissionsResponse,
  GranularityConfiguration,
  TimePeriod,
  AccessDeniedException,
  InternalServerException,
  ThrottlingException,
  ValidationException,
  SustainabilityServiceException,
  paginateGetEstimatedCarbonEmissions,
  paginateGetEstimatedCarbonEmissionsDimensionValues,
} from "../dist-types/index.d";
